//go:build !lego_acmedns && !lego_active24 && !lego_alidns && !lego_allinkl && !lego_arvancloud && !lego_auroradns && !lego_autodns && !lego_axelname && !lego_azure && !lego_azuredns && !lego_baiducloud && !lego_bindman && !lego_bluecat && !lego_bookmyname && !lego_brandit && !lego_bunny && !lego_checkdomain && !lego_civo && !lego_clouddns && !lego_cloudflare && !lego_cloudns && !lego_cloudru && !lego_cloudxns && !lego_conoha && !lego_constellix && !lego_corenetworks && !lego_cpanel && !lego_derak && !lego_desec && !lego_designate && !lego_digitalocean && !lego_directadmin && !lego_dnshomede && !lego_dnsimple && !lego_dnsmadeeasy && !lego_dnspod && !lego_dode && !lego_domeneshop && !lego_dreamhost && !lego_duckdns && !lego_dyn && !lego_dynu && !lego_easydns && !lego_edgedns && !lego_efficientip && !lego_epik && !lego_exec && !lego_exoscale && !lego_f5xc && !lego_freemyip && !lego_gandi && !lego_gandiv5 && !lego_gcloud && !lego_gcore && !lego_glesys && !lego_godaddy && !lego_googledomains && !lego_hetzner && !lego_hostingde && !lego_hosttech && !lego_httpnet && !lego_httpreq && !lego_huaweicloud && !lego_hurricane && !lego_hyperone && !lego_ibmcloud && !lego_iij && !lego_iijdpf && !lego_infoblox && !lego_infomaniak && !lego_internetbs && !lego_inwx && !lego_ionos && !lego_ipv64 && !lego_iwantmyname && !lego_joker && !lego_liara && !lego_lightsail && !lego_limacity && !lego_linode && !lego_liquidweb && !lego_loopia && !lego_luadns && !lego_mailinabox && !lego_manageengine && !lego_metaname && !lego_metaregistrar && !lego_mijnhost && !lego_mittwald && !lego_myaddr && !lego_mydnsjp && !lego_mythicbeasts && !lego_namecheap && !lego_namedotcom && !lego_namesilo && !lego_nearlyfreespeech && !lego_netcup && !lego_netlify && !lego_nicmanager && !lego_nifcloud && !lego_njalla && !lego_nodion && !lego_ns1 && !lego_oraclecloud && !lego_otc && !lego_ovh && !lego_pdns && !lego_plesk && !lego_porkbun && !lego_rackspace && !lego_rainyun && !lego_rcodezero && !lego_regfish && !lego_regru && !lego_rfc2136 && !lego_rimuhosting && !lego_route53 && !lego_safedns && !lego_sakuracloud && !lego_scaleway && !lego_selectel && !lego_selectelv2 && !lego_selfhostde && !lego_servercow && !lego_shellrent && !lego_simply && !lego_sonic && !lego_spaceship && !lego_stackpath && !lego_technitium && !lego_tencentcloud && !lego_timewebcloud && !lego_transip && !lego_ultradns && !lego_variomedia && !lego_vegadns && !lego_vercel && !lego_versio && !lego_vinyldns && !lego_vkcloud && !lego_volcengine && !lego_vscale && !lego_vultr && !lego_webnames && !lego_websupport && !lego_wedos && !lego_westcn && !lego_yandex && !lego_yandex360 && !lego_yandexcloud && !lego_zoneee && !lego_zonomi

package legotapas

import (
    "github.com/go-acme/lego/v4/challenge"
    "github.com/go-acme/lego/v4/providers/dns"
)

func CreateProvider(providerName string) (challenge.Provider, error) {
    return dns.NewDNSChallengeProviderByName(providerName)
}
