name: generate plates

on:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Generate
        run: |
          rm plate_*.go
          go run ./cmd/generate

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update plates'